name: simplot
version: 0.1.0
author: Richard Griffith (scribe.griff@gmail.com)
description: A library for plotting two dimensional (2D), list based, data structure to an HTML canvas.
homepage: https://github.com/scribeGriff/simplot
environment:
  sdk: '>=0.5.3'
dev_dependencies:
  browser: any
  convolab:
    git: git://github.com/scribeGriff/ConvoLab.git
  unittest: any

#dependencies:
#  js: any
#  unittest: any